### ISSUE TITLE
Failed to run the example with VS Code

### ISSUE THREAD

**Issue by jasonlaw** [neohelden/Flutter-AdaptiveCards#31]
Waiting for another flutter command to release the startup lock...
Launching lib\main.dart on Android SDK built for x86 in debug mode...
[!] Your app isn't using AndroidX.
    To avoid potential build failures, you can quickly migrate your app by following the steps on https://goo.gl/CP92wY.
Exception in thread "main" java.lang.RuntimeException: Timeout of 120000 reached waiting for exclusive access to file: C:\Users\jlw1\.gradle\wrapper\dists\gradle-4.4-all\9br9xq1tocpiv8o6njlyu5op1\gradle-4.4-all.zip
	at org.gradle.wrapper.ExclusiveFileAccessManager.access(ExclusiveFileAccessManager.java:61)
	at org.gradle.wrapper.Install.createDist(Install.java:48)
	at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:128)
	at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
Picked up _JAVA_OPTIONS: -Xmx2g
[!] Gradle threw an error while downloading artifacts from the network. Retrying to download...
[!] Your app isn't using AndroidX.
    To avoid potential build failures, you can quickly migrate your app by following the steps on https://goo.gl/CP92wY.
Exited (1)

**Comment by beevelop** [comment]
Looks like this issue might be caused by Flutter / Gradle itself and is not isolated to the AdaptiveCards example:
- https://github.com/flutter/flutter/issues/29100
- https://github.com/flutter/flutter/issues/45037
- https://github.com/flutter/flutter/issues/26570

Could you try running `flutter clean` and alternatively a `flutter upgrade` to update you current version?

**Comment by Curvel** [comment]
@jasonlaw do you have any updates on your issue?

**Comment by beevelop** [comment]
@jasonlaw: Feel free to reopen the issue, if you are still struggling with the example app. :v:
